// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAInCliYWaoFokYO617RtVHObBQ8-kDdSg',
    appId: '1:793888474649:web:39caf6f2b891923ebe8c88',
    messagingSenderId: '793888474649',
    projectId: 'spotify-clone-b0165',
    authDomain: 'spotify-clone-b0165.firebaseapp.com',
    storageBucket: 'spotify-clone-b0165.appspot.com',
    measurementId: 'G-P8760Y76S4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5trROcCAWP4YubnZM4NAXBLrMTY1NkT8',
    appId: '1:793888474649:android:b1979e98c0f29a49be8c88',
    messagingSenderId: '793888474649',
    projectId: 'spotify-clone-b0165',
    storageBucket: 'spotify-clone-b0165.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASjCxzoCdu1kH-SC10APaJjCvkcpHdcuM',
    appId: '1:793888474649:ios:716d0e9e2863a26fbe8c88',
    messagingSenderId: '793888474649',
    projectId: 'spotify-clone-b0165',
    storageBucket: 'spotify-clone-b0165.appspot.com',
    iosClientId: '793888474649-v3sf9bko4rf6hr4jdsuefrjrgvuv9vvr.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASjCxzoCdu1kH-SC10APaJjCvkcpHdcuM',
    appId: '1:793888474649:ios:716d0e9e2863a26fbe8c88',
    messagingSenderId: '793888474649',
    projectId: 'spotify-clone-b0165',
    storageBucket: 'spotify-clone-b0165.appspot.com',
    iosClientId: '793888474649-v3sf9bko4rf6hr4jdsuefrjrgvuv9vvr.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotify',
  );
}
